export const STRATEGY_ROUTER_ABI = [
  {
    type: 'function',
    name: 'getCurrentAPYs',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      { name: 'aaveAPY', type: 'uint256' },
      { name: 'compoundAPY', type: 'uint256' },
      { name: 'morphoAPY', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'getAaveAPY',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'getCompoundAPY',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'getMorphoAPY',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'getUserProtocolBalances',
    stateMutability: 'view',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [
      { name: 'aaveBalance', type: 'uint256' },
      { name: 'compoundBalance', type: 'uint256' },
      { name: 'morphoBalance', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'forceRebalance',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'investFunds',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'amount', type: 'uint256' },
      { name: 'user', type: 'address' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'redeemFunds',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'amount', type: 'uint256' },
      { name: 'user', type: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'setMockApys',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'aaveAPYBps', type: 'uint256' },
      { name: 'compoundAPYBps', type: 'uint256' },
      { name: 'morphoAPYBps', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setDemoMode',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'enabled', type: 'bool' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setKeeper',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'keeper_', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'demoMode',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
  },
] as const;
