export const STRATEGY_ROUTER_ABI = [
  {
    type: "event",
    name: "VaultUpdated",
    inputs: [{ name: "vault", type: "address", indexed: true }],
    anonymous: false,
  },
  {
    type: "event",
    name: "KeeperUpdated",
    inputs: [{ name: "keeper", type: "address", indexed: true }],
    anonymous: false,
  },
  {
    type: "event",
    name: "DemoModeUpdated",
    inputs: [{ name: "enabled", type: "bool", indexed: false }],
    anonymous: false,
  },
  {
    type: "event",
    name: "MockApysUpdated",
    inputs: [
      { name: "aaveAPYBps", type: "uint256", indexed: false },
      { name: "compoundAPYBps", type: "uint256", indexed: false },
      { name: "morphoAPYBps", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProtocolAddressesUpdated",
    inputs: [
      { name: "aavePool", type: "address", indexed: true },
      { name: "compoundToken", type: "address", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MorphoUpdated",
    inputs: [
      { name: "morpho", type: "address", indexed: true },
      { name: "loanToken", type: "address", indexed: false },
      { name: "collateralToken", type: "address", indexed: false },
      { name: "oracle", type: "address", indexed: false },
      { name: "irm", type: "address", indexed: false },
      { name: "lltv", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MorphoLiveApyUpdated",
    inputs: [{ name: "morphoLiveApyBps", type: "uint256", indexed: false }],
    anonymous: false,
  },
  {
    type: "event",
    name: "UserFundsInvested",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "toAave", type: "uint256", indexed: false },
      { name: "toCompound", type: "uint256", indexed: false },
      { name: "toMorpho", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "UserFundsRedeemed",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "fromAave", type: "uint256", indexed: false },
      { name: "fromCompound", type: "uint256", indexed: false },
      { name: "fromMorpho", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "UserRebalanced",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "fromProtocol", type: "uint8", indexed: false },
      { name: "toProtocol", type: "uint8", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "function",
    name: "assetToken",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "vault",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "keeper",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "demoMode",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "mockAaveAPYBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "mockCompoundAPYBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "mockMorphoAPYBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getAaveAPY",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getCompoundAPY",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getMorphoAPY",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getCurrentAPYs",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "aaveAPYBps", type: "uint256" },
      { name: "compoundAPYBps", type: "uint256" },
      { name: "morphoAPYBps", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "getUserProtocolBalances",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [
      { name: "aaveBalance", type: "uint256" },
      { name: "compoundBalance", type: "uint256" },
      { name: "morphoBalance", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "totalManagedAssets",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "setVault",
    stateMutability: "nonpayable",
    inputs: [{ name: "vault_", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setKeeper",
    stateMutability: "nonpayable",
    inputs: [{ name: "keeper_", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setProtocolAddresses",
    stateMutability: "nonpayable",
    inputs: [
      { name: "aavePool_", type: "address" },
      { name: "compoundToken_", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setMorpho",
    stateMutability: "nonpayable",
    inputs: [
      { name: "morpho_", type: "address" },
      {
        name: "marketParams_",
        type: "tuple",
        components: [
          { name: "loanToken", type: "address" },
          { name: "collateralToken", type: "address" },
          { name: "oracle", type: "address" },
          { name: "irm", type: "address" },
          { name: "lltv", type: "uint256" },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setMorphoLiveApyBps",
    stateMutability: "nonpayable",
    inputs: [{ name: "morphoLiveApyBps_", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setDemoMode",
    stateMutability: "nonpayable",
    inputs: [{ name: "enabled", type: "bool" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setMockApys",
    stateMutability: "nonpayable",
    inputs: [
      { name: "aaveAPYBps", type: "uint256" },
      { name: "compoundAPYBps", type: "uint256" },
      { name: "morphoAPYBps", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "investFunds",
    stateMutability: "nonpayable",
    inputs: [
      { name: "amount", type: "uint256" },
      { name: "user", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "redeemFunds",
    stateMutability: "nonpayable",
    inputs: [
      { name: "amount", type: "uint256" },
      { name: "user", type: "address" },
    ],
    outputs: [{ name: "withdrawn", type: "uint256" }],
  },
  {
    type: "function",
    name: "rebalance",
    stateMutability: "nonpayable",
    inputs: [{ name: "user", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "forceRebalance",
    stateMutability: "nonpayable",
    inputs: [{ name: "user", type: "address" }],
    outputs: [],
  },
] as const;
